### ISSUE TITLE
Querying posts on blockchain with permlink and author?

### ISSUE THREAD

**Issue by SquidLord** [holgern/beem#1]
I have an interesting problem which should be solvable with Beem, but which I can't quite seem to figure out how to put into the context of the module UI.

Here's my problem:

I have a list of permlinks and authors, and I want to walk this list and accumulate certain post attributes which they have.

I've been using SteamData to acquire slices of voting data and account names, and that works just fine – but once I have a list of specifics to investigate further, it's very difficult to get a MongoDB query that runs in a reasonable time which is efficient for pulling back a long list of specific items.

This seems like something that is tailor-made for Beem.

Unfortunately, I can't figure out from the documentation as it stands how one would go about simply formulating that function or method call. It's fairly easy to watch the blockchain for specific changes in a streaming way, but it is nontrivial to query the blockchain for specific information.

Am I just missing something obvious, or is that functionality not implemented yet, or am I trying to use the wrong tool for the wrong job?

**Comment by holgern** [comment]
from beem.comment import Comment
c =Comment({"author": "abc", "permlink": "Postabc"})
