### ISSUE TITLE
Suggestion: get_witnesses(witness_ids: list)

### ISSUE THREAD

**Issue by themarkymark-steem** [holgern/beem#109]
This is a very useful function from, Steem-python for getting multiple but not all witnesses in a single RPC call.  Would be great to see it added to Beem.

**Comment by holgern** [comment]
Issue fixed:
```
from beem.witness import GetWitnesses
w = GetWitnesses(["gtg", "jesta"])
print(w[0].json())
print(w[1].json())
```
