### ISSUE TITLE
Invalid cast from array_type to string in GetWitnesses

### ISSUE THREAD

**Issue by themarkymark-steem** [holgern/beem#113]
Thanks for the GetWitnesses() function.
It works great on Steem, but on Vit I noticed it throws the following error.

```
Invalid cast from array_type to string
    {"type":"array_type"}
    th_a  variant.cpp:478 as_string
```

I tried just using one witness (in a list) and a list of them, both fail with a similar error.

**Comment by holgern** [comment]
Should be fixed in 0,20.10
