### ISSUE TITLE
Can't install beem due to Scrypt installation error (Windows): 'openssl/aes.h': No such file or directory

### ISSUE THREAD

**Issue by CryptoSharon** [holgern/beem#114]
I was trying to do `pip install beem` in order to run your steemmonsters app, but beem depends on Scrypt, and Scrypt doesn't seem to be able to run on Windows. I tried to install the OpenSSL package that it requires, but I failed. I don't exactly know what else it needs. I installed [this](http://gnuwin32.sourceforge.net/packages/openssl.htm) and added it to my path.

The following is the error that I got.

```
    crypto_aes.c
    scrypt-1.2.1/libcperciva/crypto/crypto_aes.c(6): fatal error C1083: No se puede abrir el archivo incluir: 'openssl/aes.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python37\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-6w9w987_\\scrypt\\setup.py';
f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();
exec(compile(code, __file__, 'exec'))
"install --record C:\Users\pc\AppData\Local\Temp\pip-record-eu_c56pk\install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in
C:\Users\pc\AppData\Local\Temp\pip-install-6w9w987_\scrypt\
```

**Comment by holgern** [comment]
The easiest solution is to install anaonda and do a conda install beem

**Comment by CryptoSharon** [comment]
OMG it's 631 MB on Conda just to install Beem. I'll do it but wow!

**Comment by CryptoSharon** [comment]
Alright, that works. Installed Miniconda, opened admin console and conda-installed beem, then with the same admin console I did python setup install steemmonsters and it didn't throw errors. I'm stuck at Steemmonsters now and can't run it but that's another issue. Beem is done.
