### ISSUE TITLE
Signing operations from Python2 throw beem.exceptions.InvalidWifError 

### ISSUE THREAD

**Issue by pibara-utopian** [holgern/beem#115]
Signing operations that work correctly when invoked from a script running in the Python3 interpreter throw a beem.exceptions.InvalidWifError when the script is run in the Python 2 interpreter.

See this link for a more complete description:

https://steemit.com/utopian-io/@mattockfs/signing-python-2-beem-scripts-stopped-working

**Comment by holgern** [comment]
Is fixed
