### ISSUE TITLE
Discussions_by_comments fails on Vit

### ISSUE THREAD

**Issue by themarkymark-steem** [holgern/beem#116]
Using the following sample code

```
from beem.discussions import Query, Discussions_by_comments
q = Query(limit=10, start_author="jat", start_permlink="firstpost")
for h in Discussions_by_comments(q):
    print(h)
```

I get an error `UnhandledRPCError: Comment is not in account's comments` when used on Vit.  I tried to give it a `steem_instance=stm` even though I am using a shared instance, it still does not work.

**Comment by crokkon** [comment]
The comment `jat/firstpost` doesn't seem to exist - are you sure the authorperm is correct?
`Comment(jat/firstpost)` throws a `ContentDoesNotExistsException`.

Your example works with 
```
q = Query(limit=10, start_author="jat", start_permlink="20181103t184336743z")
```

**Comment by themarkymark-steem** [comment]
My bad, I had a user from one chain, but the permlink was from other chain.
Going to close this.
