### ISSUE TITLE
Conda installed 'beem' on Debian but only "beempy" is in conda's /bin - "ImportError: No module named 'beem'"

### ISSUE THREAD

**Issue by CryptoSharon** [holgern/beem#121]
I'm setting up beem in a new server and wanted to install it, so I tried with pip, but the same error as on Windows appears (scrypt is not very good at being installed from pip). I installed conda then did `conda install -c conda-forge beem`, and it went alright. But now if I try to import it into my script, I get the error "ImportError: No module named 'beem'" even though it's in the /bin as "beempy".

**Comment by holgern** [comment]
Should be fixed, or?
