### ISSUE TITLE
encrypted memo problem

### ISSUE THREAD

**Issue by economicstudio** [holgern/beem#168]
There are two problems with encrypted memo

1. allowed length is quite short and not consistent depending on the memo text
2. first character is removed with a long encrypted memo

For instance,
memo = '#123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890'

What I received is
#2345678901234567890123456789012345678901234567890

Interestingly, with steem-python
#12345678901234567890123456789012345 (shorter, but it has the first character)

If I try with different memo (some real text), the max length delivered was different.

In any case, it's much shorter than the limit (how long is it by the way?) allowed, compared to steemsql subscription encrypted memo that I received.

**Comment by holgern** [comment]
Fixed in release 0.23.12.
