### ISSUE TITLE
[Beem] [Version: 0.20.19] Account.get_balance function shows summed value of liquid balance and unclaimed reward

### ISSUE THREAD

**Issue by sourovafrin** [holgern/beem#171]
#### Expected behavior

```
from beem.account import Account

acc=Account("eftikhan")
inf=acc.get_balances()
steem=inf['available'][0]
sbd=inf['available'][1]

print("steem {} and sbd {}".format(steem, sbd))
```

Account.get_balance function should  Return all account balances as dictionary. As i have filtered the steem and sbd here it should return the actual liquid balance of steem and sbd

#### Actual behavior

When the Account.get_balance function is called, it shows the account's steem and sbd balance summed with unclaimed reward. on `eftikhan` account the actual sbd balance is `0.412` but beem shows it `0.503` as it summed `0.091` unclaimed sbd which should not have happened here.

#### How to reproduce

```
from beem.account import Account

acc=Account("username")
inf=acc.get_balances()
steem=inf['available'][0]
sbd=inf['available'][1]

print("steem {} and sbd {}".format(steem, sbd))
```

- Install latest version of beem and run this code.

- Take an account which has unclaimed reward.

- Put that account's username on **username** and run the code.

- You will see the balance is showing more than steemit shows as it summed up the unclaimed reward.

#### Technical analysis

https://github.com/holgern/beem/blob/1364f732e94d9347682f2869eaec61553555ca63/beem/account.py#L917
over here you see,
``` 
ret = []
        for i in range(len(symbols)):
            balance_sum = self.get_balance(self.available_balances, symbols[i])
            balance_sum += self.get_balance(self.saving_balances, symbols[i])
            balance_sum += self.get_balance(self.reward_balances, symbols[i])
            ret.append(balance_sum)
        return ret
```
This issue is happening because of += sign. From this we also came to know, it would sum up the the savings balance as well.

#### Possible fix

``` 
ret = []
        for i in range(len(symbols)):
            balance_sum = self.get_balance(self.available_balances, symbols[i])
            balance_sum = balance_sum + self.get_balance(self.saving_balances, symbols[i])
            balance_sum = balance_sum + self.get_balance(self.reward_balances, symbols[i])
            ret.append(balance_sum)
        return ret
```

#### Recording Of The Bug

https://youtu.be/C_YfGNRIyk8

- Python 3.6

- Beem version 0.20.19

- Operating system: Ubuntu 18.06

**Comment by holgern** [comment]
Thanks for reporting the issue, I applied your suggestion and it should be fixed now.
