### ISSUE TITLE
Whaleshares support broken for nodes running on v0.2.7.

### ISSUE THREAD

**Issue by tiotdev** [holgern/beem#188]
Whaleshares does not work anymore with nodes operating on v0.2.7 (https://gitlab.com/beyondbitcoin/whaleshares-chain/tags/v0.2.7). As of now, there are no public nodes working with beem.

**Comment by anthonyadavisii** [comment]
Try the node I used here:

https://whaleshares.io/@anthonyadavisii/whaleshares-post-history-and-how-to-get-yours-with-beem

What functionality are you referencing? Just connection or something else?

**Comment by tiotdev** [comment]
Whaleshares changed their whole API for broadcasting transactions to the Blockchain recently and neither their official Python library nor beem has been updated to support the new version. I tried to manually broadcast transactions using the new API structure, but it does not accept the signature ("missing required posting authority") https://gist.github.com/tiotdev/ffdecb9992e7163f7cf483aaaa01ebce

**Comment by alexpmorris** [comment]
https://github.com/holgern/beem/pull/192

**Comment by holgern** [comment]
Will be fixed in 0.20.22
