### ISSUE TITLE
proposal for beem logo

### ISSUE THREAD

**Issue by ivannewgate89** [holgern/beem#2]
can i join? i have idea for this logo )

**Comment by holgern** [comment]
Yes, if you have an account on steemit.
Time: Submitions are accepted withing 11 April 00:00 UTC to 13 April 23:59 UTC
Submit your idea to as comment
https://utopian.io/utopian-io/@holger80/logo-request-for-beem-a-python-library-for-steem

**Comment by ivannewgate89** [comment]
of course, i have finished his job, and i will post on 11 april 18, thanks.
do i have to post to you my link posting in this github?,

**Comment by holgern** [comment]
no, no need

**Comment by ivannewgate89** [comment]
okey thanks, i just post in utopian

**Comment by ivannewgate89** [comment]
hi holger, this is my link https://utopian.io/utopian-io/@ivannewgate89/logo-for-beem-a-python-library-for-steem, please check )

**Comment by holgern** [comment]
Good work!
Can you write a comment under my task request and add an image of your contribution and add a link to your post?
My task request link:
https://utopian.io/utopian-io/@holger80/logo-request-for-beem-a-python-library-for-steem
