### ISSUE TITLE
UnhandledRPCError: Assert Exception:_follow_api: follow_api_plugin not enabled.

### ISSUE THREAD

**Issue by donteatyellowsno** [holgern/beem#217]
I tried reinstalling my Beem in different ways (pip install -U beem and the github setup.py way). I still dont manage to make this simple code work:
`from beem.account import Account

acc=Account("gtg")

for h in acc.get_feed():

    print(h)`
I thought it might be a node fault but I have problems with both
https://steemd.minnowsupportproject.org/ and https://api.steemit.com/
.get_account_history() works fine though...
when i go to terminal and type
`curl -s --data '{"jsonrpc"pi.get_feed", "params":{"account":"gtg","start_entry_id":0,"limit":1}, "id":1}' https://api.steemit.com
`
as prescribed on the https://developers.steem.io/apidefinitions/follow-api steem website
i get
`{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":"follow_api.get_feed"},"id":1}`

**Comment by holgern** [comment]
This should be fixed now with 0.22.14
