### ISSUE TITLE
BEEM APP FAIL TO UPLOAD AVATAR

### ISSUE THREAD

**Issue by anikys3reasure** [holgern/beem#22]
Project Information
* Repository
https://github.com/holgern/beem

* Project Name - **BEEM APP**

* **Expected Behavior** 
**SUPPORT OF USER AVATAR** (User should be able to Upload **AVATAR** when Updating Status).

* **Actual Behavior**
**NOT SUPPORTING USERS AVATAR** (Application fail to Upload Avatar, thereby denying user of providing an Image for other users to see).

* **How To Reproduce**;
1. Download and Install Beem-Chat App from Google play store 

2. Open the application to create an account or use an existing account.

3.  Click  the three dots on the right upper part and choose **Change status** from the listed menu.

4. Click on the avatar icon to upload an image, then **it fails to upload the avatar**.

* Device - Infinix Hot X521 
* Operating System - Android 6.0
Application Version - v0.1.8

Recording of the Bug
https://www.youtube.com/watch?v=P4r4AZaJvfk

**Comment by holgern** [comment]
This github repo is about a python library for steem, not related to a android app.

**Comment by E-D-A** [comment]
Too bad... I was excited for a short while that you developed some kind of app for beem. ;)
