### ISSUE TITLE
HIVE: Account balances doesn't update after BUY or SELL.

### ISSUE THREAD

**Issue by spaninv** [holgern/beem#224]
Hi,

When using beem 0.22.10 with HIVE, my account balance doesn't update after use BUY or SELL in the market.

I check the balance in a loop using account.get_balance("available", "HIVE") and performs the BUY and SELL orders in https://wallet.hive.blog/market

If i restart the script, i receive the updated balance without problems.

Thanks in advance.

**Comment by E-D-A** [comment]
Hi, sounds like you are not using a refresh() to fetch the new values. Data is cached to avoid unnecessary api calls.

**Comment by spaninv** [comment]
Great. Lot of thanks.
