### ISSUE TITLE
beempy updatenodes: -h mapped twice

### ISSUE THREAD

**Issue by crokkon** [holgern/beem#228]
`-h` is mapped both to `--hive` and `--only-https`, https is later and takes priority:
https://github.com/holgern/beem/blob/b782b2ad72c7caeb880842c4f0c5ff724c86f127/beem/cli.py#L434
https://github.com/holgern/beem/blob/b782b2ad72c7caeb880842c4f0c5ff724c86f127/beem/cli.py#L443

**Comment by holgern** [comment]
Thanks, has been fixed in 0.23.0
