### ISSUE TITLE
Unable to Claim Specific Reward Asset

### ISSUE THREAD

**Issue by inertia186** [holgern/beem#289]
*As a tool developer, I would like the ability to claim a specific reward asset, so that it is not all or nothing.*

Claiming all reward assets at once works as expected (by passing zero arguments, [as documented](https://beem.readthedocs.io/en/latest/beem.account.html#beem.account.Account.claim_reward_balance)).  But when claiming a specific asset, for example:

```python
account = Account('inertia')
account.claim_reward_balance(reward_vests=10)
```

... I get the following error:

```
Traceback (most recent call last):
.
.
.
  File "/usr/local/lib/python3.9/site-packages/beem/account.py", line 3190, in claim_reward_balance
    return self.blockchain.finalizeOp(op, account, "posting", **kwargs)
UnboundLocalError: local variable 'op' referenced before assignment
```

It appears to me that the arguments specifying a single asset result in unreachable code.

https://github.com/holgern/beem/blob/d9b9f96cbe77073c07083a0a98974b1988cf429e/beem/account.py#L3166-L3190

**AC**

- [ ] Able to claim any combination of reward assets.

**Comment by holgern** [comment]
There was a not complete conditional structure, it should be fixed by now
