### ISSUE TITLE
SteemConnect expects double quotes in JSON

### ISSUE THREAD

**Issue by crokkon** [holgern/beem#57]
#### Expected behavior
The URL created from a transaction via `steemconnect.url_from_tx()` should be able to create the according transaction via SteemConnect.

#### Actual behavior
Parts of the JSON values are wrapped in single quotes (e.g. `'value'`) instead of double quotes (e.g. `"value"`), leading to JSON parsing errors with the created steemconnect link

#### How to reproduce
```python
from beem import Steem
from beem.steemconnect import SteemConnect
s = Steem(nobroadcast=True, unsigned=True)
sc = SteemConnect(steem_instance=s)
tx = s.custom_json("123", {'field1': 'data1', 'field2': 'data2'}, required_posting_auths=["stmdev"])
print(sc.url_from_tx(tx))
```

Result:
```
https://v2.steemconnect.com/sign/custom_json?required_auths=%5B%5D&required_posting_auths=%5B%27stmdev%27%5D&id=123&json=%7B%22field1%22%3A+%22data1%22%2C+%22field2%22%3A+%22data2%22%7D
```
Note the `%27`=`'` around `stmdev`, but `%22`=`"` around the actual payload.

![screenshot_2018-07-18_16-53-14](https://user-images.githubusercontent.com/33018033/42889616-25f17de6-8aab-11e8-971e-e05abdb331e1.png)

By modifying the URL to replace all `%27` with `%22` the URL works:
```
https://steemconnect.com/sign/custom_json?required_auths=%5B%5D&required_posting_auths=%5B%22stmdev%22%5D&id=123&json=%7B%22field1%22%3A+%22data1%22%2C+%22field2%22%3A+%22data2%22%7D
```
![screenshot_2018-07-18_16-54-41](https://user-images.githubusercontent.com/33018033/42889696-54ebf5f4-8aab-11e8-94ef-4dd38a4f05f0.png)

gregory-f from steemconnect confirmed that the "pure JSON" / SteemConnect expects double quotes.

#### Environment
* beem 0.19.49
* python 3.6.5

**Comment by holgern** [comment]
After doing some research, I fixed the issue by a simple:
```
params = urlencode(params).replace("%27", "%22")
```
Hope this will work.

**Comment by crokkon** [comment]
will certainly work for 99% of the cases, but this also replaces single quotes in the payload:
```python
from beem import Steem
from beem.steemconnect import SteemConnect
s = Steem(nobroadcast=True, unsigned=True)
sc = SteemConnect(steem_instance=s)
tx = s.custom_json("123", {'field1': "data with 'quotes'", 'field2': 'data2'}, required_posting_auths=["stmdev"])
print(sc.url_from_tx(tx))
```
```
https://v2.steemconnect.com/sign/custom_json?required_auths=%5B%5D&required_posting_auths=%5B%22stmdev%22%5D&id=123&json=%7B%22field1%22%3A+%22data+with+%22quotes%22%22%2C+%22field2%22%3A+%22data2%22%7D
```

**Comment by holgern** [comment]
Thanks, I will use your solution, looks cleaner.
