### ISSUE TITLE
Blockchain.get_transaction / get_transaction_hex issues on appbase

### ISSUE THREAD

**Issue by crokkon** [holgern/beem#64]
#### Expected behavior
`Blockchain.get_transaction` should return the transaction for a given transaction id
`Blockchain.get_transaction_hex` should return a hexdump of the serialized binary form of a transaction

#### Actual behavior
`Blockchain.get_transaction` and `Blockchain.get_transaction_hex` fail on appbase nodes with `Could not find method get_transaction`

#### How to reproduce
```python
from beem import Steem
from beem.blockchain import Blockchain
trx_id = '6fde0190a97835ea6d9e651293e90c89911f933c'
s = Steem(node=['https://api.steemit.com'])
b = Blockchain(steem_instance=s)
print(b.get_transaction(trx_id))
```

```python
from beem import Steem
from beem.blockchain import Blockchain
trx = {"ref_block_num":1097,"ref_block_prefix":2181793527,"expiration":"2016-03-24T18:00:21","operations":[{"type":"pow_operation","value":{"worker_account":"cloop3","block_id":"00000449f7860b82b4fbe2f317c670e9f01d6d9a","nonce":3899,"work":{"worker":"STM7P5TDnA87Pj9T4mf6YHrhzjC1KbPZpNxLWCcVcHxNYXakpoT4F","input":"ae8e7c677119d22385f8c48026fee7aad7bba693bf788d7f27047f40b47738c0","signature":"1f38fe9a3f9989f84bd94aa5bbc88beaf09b67f825aa4450cf5105d111149ba6db560b582c7dbb026c7fc9c2eb5051815a72b17f6896ed59d3851d9a0f9883ca7a","work":"000e7b209d58f2e64b36e9bf12b999c6c7af168cc3fc41eb7f8a4bf796c174c3"},"props":{"account_creation_fee":{"amount":"100000","precision":3,"nai":"@@000000021"},"maximum_block_size":131072,"sbd_interest_rate":1000}}}],"extensions":[],"signatures":[]}
s = Steem(node=['https://api.steemit.com'])
b = Blockchain(steem_instance=s)
print(b.get_transaction_hex(trx))
```

---

The problem with `get_transaction_hex()` is a typo, the function internally calls `get_transaction()` instead of `get_transaction_hex()`.

`get_transaction()` tries to use `database_api`. However, this method is not part of database_api. According to the documentation, it's only part of `condenser_api`. Changing the API to `"condenser"` results in a `account_history_api_plugin not enabled` Exception. This exception is also thrown with the example in the [official documentation](https://developers.steem.io/apidefinitions/#condenser_api.get_transaction-curl-examples). I have no idea how to fix `get_transaction()` for appbase nodes.

#### Environment
```
# python --version
Python 3.6.6
# beempy --version
beempy, version 0.19.50
```

**Comment by holgern** [comment]
The error message for `get_transaction()` is now: `
beemapi.exceptions.ApiNotSupported: Assert Exception:api_itr != _registered_apis.end(): Could not find API account_history_api`
It's fails now because the  API is not activated on the RPC noce.
