### ISSUE TITLE
Move Changelog from README.rst 

### ISSUE THREAD

**Issue by Jestemkioskiem** [holgern/beem#80]
With how enormous the changelog is, it makes the `README.rst` file (which, as the name implies, should be read in it's entirety) much too long. 

With the frequent updates to beem, keeping the changelog there is unsustainable. I propose moving it to an another file (`changelog.rst`?) or into the Wiki pages of the repository.

**Comment by holgern** [comment]
Thanks for the suggestions, it is now fixed.
